/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/ui/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./components/ui/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./components/ui/accordion/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./components/ui/accordion/AccordionTrigger.vue')['default']
    Badge: typeof import('./components/ui/badge/Badge.vue')['default']
    BukaKartu: typeof import('./components/games/BukaKartu.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    GameSwitcher: typeof import('./components/shared/GameSwitcher.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    KocokAmplop: typeof import('./components/games/KocokAmplop.vue')['default']
    Navbar: typeof import('./components/shared/Navbar.vue')['default']
    NominalChip: typeof import('./components/setup/NominalChip.vue')['default']
    NominalForm: typeof import('./components/setup/NominalForm.vue')['default']
    ResultModal: typeof import('./components/shared/ResultModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
