/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BukaKartu: typeof import('./components/games/BukaKartu.vue')['default']
    GameSwitcher: typeof import('./components/shared/GameSwitcher.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    KocokAmplop: typeof import('./components/games/KocokAmplop.vue')['default']
    Navbar: typeof import('./components/shared/Navbar.vue')['default']
    NominalChip: typeof import('./components/setup/NominalChip.vue')['default']
    NominalForm: typeof import('./components/setup/NominalForm.vue')['default']
    ResultModal: typeof import('./components/shared/ResultModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
